# Database Library Author: Smudge
# File: database.yml
# Last Changed Library Version: 1.0.0

should_reconnect_every_cycle: true
reconnect_cooldown_millis: 2000
will_reconnect: true
time_between_requests_millis: 100
max_requests_pending: 40

sqlite:
  enabled: true
  path: "plugins/CozyJoinLeave/database.sqlite3"

mysql:
  enabled: false
  connection_string: "address:port"
  database_name: ""
  username: ""
  password: ""

mongo:
  enabled: false
  connection_string: "" # example: "mongodb+srv://Name:Password@Name.?.mongodb.net/?retryWrites=true&w=majority"
  database_name: ""